import QRCode from "qrcode";
import { headers } from "next/headers";

interface Props {
  token: string;
  size?: number;
  className?: string;
}

/**
 * Server component that renders a member's check-in QR as an inline SVG.
 *
 * The QR encodes the full member-portal URL (`https://<host>/m/<token>`) so a
 * generic phone camera (Google Lens, iOS Camera, etc.) shows a tappable link.
 * The in-app check-in scanner extracts the token from the URL — both forms work.
 */
export async function MemberQRCode({ token, size = 200, className }: Props) {
  const h = await headers();
  const host = h.get("x-forwarded-host") ?? h.get("host") ?? "";
  const proto = h.get("x-forwarded-proto") ?? (host.startsWith("localhost") ? "http" : "https");
  const url = host ? `${proto}://${host}/m/${token}` : `/m/${token}`;

  const svg = await QRCode.toString(url, {
    type: "svg",
    errorCorrectionLevel: "M",
    margin: 1,
    width: size,
    color: {
      dark: "#0f172a",
      light: "#ffffff",
    },
  });

  return (
    <div
      className={className}
      // SVG markup is generated by qrcode lib — safe to inject
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
