import QRCode from "qrcode";

interface Props {
  token: string;
  size?: number;
  className?: string;
}

/**
 * Server component that renders a member's check-in QR as an inline SVG.
 * The QR encodes just the token (not a URL) — the check-in scanner reads it
 * and looks up the member directly. Smaller QR = easier to scan in poor light.
 */
export async function MemberQRCode({ token, size = 200, className }: Props) {
  const svg = await QRCode.toString(token, {
    type: "svg",
    errorCorrectionLevel: "M",
    margin: 1,
    width: size,
    color: {
      dark: "#0f172a",
      light: "#ffffff",
    },
  });

  return (
    <div
      className={className}
      // SVG markup is generated by qrcode lib — safe to inject
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
